#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/integration_blueprint
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Copy Lovelace card assets to config/www so they are served at /local/
mkdir -p "${PWD}/config/www"
cp -r "${PWD}/custom_components/pollen_dk/www/." "${PWD}/config/www/"

# Start Home Assistant
hass --config "${PWD}/config" --debug