#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

wget https://github.com/AlexxIT/go2rtc/releases/download/v1.9.14/go2rtc_linux_arm64
sudo mv go2rtc_linux_arm64 /bin/go2rtc
sudo chmod +x /bin/go2rtc